M48
; DRILL file KiCad 10.0.1 date 2026-04-25T15:45:38
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-25T15:45:38-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
%
G90
G05
T1
X147.1Y-113.6
X147.1Y-118.6
T2
X113.24Y-108.5
X113.24Y-111.5
T3
X114.0Y-103.0
X114.0Y-128.0
X149.0Y-103.0
X149.0Y-128.0
M30
